-- Customer sales summary

SELECT
    CUSTOMER_ID,
    COUNT(*) AS ORDER_COUNT,
    SUM(COALESCE(ORDER_AMOUNT, 0)) AS TOTAL_SALES,
    AVG(COALESCE(ORDER_AMOUNT, 0)) AS AVG_ORDER_VALUE
FROM SALES_DB.RAW.ORDERS
WHERE ORDER_DATE >= DATEADD(MONTH, -6, CURRENT_DATE())
GROUP BY CUSTOMER_ID
HAVING SUM(COALESCE(ORDER_AMOUNT, 0)) > 1000
ORDER BY TOTAL_SALES DESC;
